In [1]:
from __future__ import print_function
import numpy as np


In [2]:
data1=[1,2,3,4,5]
arr1= np.array(data1)
data2=[range(1,5),range(5,9)]
arr2= np.array(data2)
arr2.tolist()

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# gives 2D array with 3 rows and 10 columns
np.zeros((3,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [8]:
# type casting of data in array int to float
int_array= np.arange(5)      
int_array
float_array= int_array.astype(float)
float_array

array([0., 1., 2., 3., 4.])

In [9]:
# examing the types of array
arr1.dtype

dtype('int32')

In [10]:
arr2.dtype


dtype('int32')

In [11]:
arr1.ndim

1

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.size

8

In [14]:
arr2.shape

(2, 4)

In [15]:
len(arr2)

2

In [16]:
arr= np.arange(10,dtype=float).reshape((2,5))
arr

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [17]:
arr.shape

(2, 5)

In [18]:
print(arr.reshape(5,2))


[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [19]:
a= np.array([0,1])
a_col= a[:,np.newaxis]
print(a_col)
a_col= a[:,None]

[[0]
 [1]]


In [20]:
print(a_col.T)

[[0 1]]


In [21]:
arr_flt= arr.flatten()
arr_flt

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
arr_flt[0]=33
print(arr_flt)
print(arr)

[33.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [23]:
arr_flt= arr.ravel()
arr_flt

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [24]:
a= np.array([0,1])
b=np.array([2,3])
ab= np.stack((a,b))
print(ab)

[[0 1]
 [2 3]]


In [25]:
arr= np.arange(9, dtype=float).reshape((3,3))
print(arr)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [26]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 print(arr[0])
print(arr[0,2])
print(arr[1][2])

[0. 1. 2.]
2.0
5.0


In [27]:
arr[0,:]

array([0., 1., 2.])

In [28]:
arr[:,0]

array([0., 3., 6.])

In [29]:
arr

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [30]:
arr[1:,:2]

array([[3., 4.],
       [6., 7.]])

In [31]:
arr[0:2,1:]

array([[1., 2.],
       [4., 5.]])

In [32]:
arr[1:,:-1]

array([[3., 4.],
       [6., 7.]])

In [33]:
arr

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [34]:
arr= np.arange(16).reshape(4,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [35]:
arr[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [36]:
arr[1:,1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [37]:
arr[1:,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [38]:
arr[2:,:-2]

array([[ 8,  9],
       [12, 13]])

In [39]:
arr[2:-1,1:-1]

array([[ 9, 10]])

In [40]:
arr[2:,2:]

array([[10, 11],
       [14, 15]])

In [41]:
my_arr= np.array([[1,2,3],[5,6,7]])
my_arr

array([[1, 2, 3],
       [5, 6, 7]])

In [42]:
a=np.array([1,2])
b=np.array([3,4])
ab= np.stack((a,b)).T
ab


array([[1, 3],
       [2, 4]])

In [43]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
arr[0,::-1]

array([3, 2, 1, 0])

In [58]:
arr[:,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8],
       [15, 14, 13, 12]])

In [46]:
arr[::-1]

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [47]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
arr_1= arr[[2,3],[1,2]]
arr_1

array([ 9, 14])

In [67]:
arr_1= arr[arr>10]
arr_1

array([11, 12, 13, 14, 15])

In [69]:
arr_1= arr*2
arr_1

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [70]:
arr_1= arr[arr<6]
arr_1

array([0, 1, 2, 3, 4, 5])

In [76]:
names= np.array(['Bob','Janny','Herry','Joey'])

In [77]:
names=='Bob'

array([ True, False, False, False])

In [78]:
names[names!='Bob']

array(['Janny', 'Herry', 'Joey'], dtype='<U5')

In [79]:
(names == 'Bob')|(names== 'Joey')

array([ True, False, False,  True])

In [80]:
names

array(['Bob', 'Janny', 'Herry', 'Joey'], dtype='<U5')

In [82]:
names[names!='Bob']= 'Joey'
names

array(['Bob', 'Joey', 'Joey', 'Joey'], dtype='<U5')

In [83]:
np.unique(names)

array(['Bob', 'Joey'], dtype='<U5')

In [95]:
nums= np.arange(5)
nums

array([0, 1, 2, 3, 4])

In [96]:
nums*10

array([ 0, 10, 20, 30, 40])

In [97]:
nums= np.sqrt(nums)
nums

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [98]:
np.ceil(nums)

array([0., 1., 2., 2., 2.])

In [99]:
np.isnan(nums)

array([False, False, False, False, False])

In [100]:
nums+np.arange(5)

array([0.        , 2.        , 3.41421356, 4.73205081, 6.        ])

In [101]:
np.ceil(nums)

array([0., 1., 2., 2., 2.])

In [102]:
np.maximum(nums,np.array([1,-2,3,-4,5]))

array([1.        , 1.        , 3.        , 1.73205081, 5.        ])

In [104]:
vec1=np.random.randn(10)
vec1

array([ 0.04747469,  0.4298141 ,  0.37224596,  1.21459128, -0.65739377,
        0.00937352, -1.65019027, -0.6879368 , -1.43919213, -0.89262189])

In [105]:
vec2=np.random.randn(10)
vec2

array([-0.08057732,  0.02604028, -2.10764436,  0.06844672, -1.75119231,
       -1.1336627 ,  0.30775156,  1.04671577, -0.30191121, -1.20611519])

In [106]:
np.sqrt(np.sum((vec1-vec2)**2))

4.287202199374886

In [110]:
rnd= np.random.randn(4,2)
rnd

array([[-0.21256219, -0.43558273],
       [-1.61548659,  0.3980905 ],
       [-0.43728483,  0.3358462 ],
       [ 0.56929115, -0.51387054]])

In [111]:
rnd.mean()

-0.23894487974651515

In [112]:
rnd.std()

0.6556100944456491

In [113]:
rnd.argmin()

2

In [114]:
rnd.sum(axis=0)

array([-1.69604246, -0.21551658])

In [115]:
rnd.sum(axis=1)

array([-0.64814492, -1.21739609, -0.10143863,  0.05542061])

In [116]:
(rnd>0).sum()

3

In [117]:
(rnd>0).any()

True

In [118]:
(rnd>0).all()

False

In [122]:
np.random.seed(12233)
np.random.rand(2,3)

array([[0.05365932, 0.5235968 , 0.29504019],
       [0.91849674, 0.38277192, 0.74727789]])

In [123]:
np.random.randn(10)

array([-0.90916109, -0.56930955,  1.14157433, -2.3529997 , -0.58003993,
        0.48227429, -0.77438052, -0.27171243,  0.98577908, -1.54014205])

In [127]:
np.random.randint(0,100,10)

array([70, 37, 71, 78, 78, 73, 95, 13, 75, 46])

In [131]:
a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b=np.array([0,1,2])

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [156]:
X= np.random.randn(4,2)
X

array([[-1.71392453, -1.02161899],
       [-0.18759639, -0.75025526],
       [ 1.14807195, -1.85810216],
       [ 0.75846765,  0.52213558]])

In [167]:
min_va= X.min(axis=0)
min_in=np.where(X.min(axis=0))
min_in

(array([0, 1], dtype=int32),)

In [158]:
np.where(X == np.amin(X,axis=0))

(array([0, 2], dtype=int32), array([0, 1], dtype=int32))

In [169]:
def standarized(X):
    x_norm= (X-np.mean(X))/np.std(X)
    return x_norm

xx=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(xx)
standarized(xx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])